import type { Metadata } from 'next'
import { Barlow, Inter } from 'next/font/google'
import './globals.css'
import { BottomFloatingBar, Footer, Navbar } from './components'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const barlow = Barlow({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-barlow',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${barlow.variable} font-sans`}>
        <div>
          <Navbar />
          <div className="top-[100px] relative">
            {children}
            <Footer />
          </div>
          <BottomFloatingBar />
        </div>
      </body>
    </html>
  )
}
